### ISSUE TITLE
Fields to filled 

### ISSUE THREAD

**Issue by NikhilDoWhile** [Mhyles/DonaldTrumpStockMonitor#10]
**What has to be filled in these fields**

**twitter_names.txt:**
Name of twitter handle/user, or email or else

![t10](https://cloud.githubusercontent.com/assets/9911561/22499573/a62edf18-e885-11e6-993b-6e76b912533c.PNG)

**emails.txt:**
whose email has to be there

![t11](https://cloud.githubusercontent.com/assets/9911561/22499620/e60a0982-e885-11e6-97b5-172f49316364.PNG)

**config.json:**
does these fields needed to be filled

![t12](https://cloud.githubusercontent.com/assets/9911561/22499630/f62bf410-e885-11e6-96e3-e500ced84384.PNG)

Is it possible to monitor multiple users, else then trump? Like we want to monitor 4-5 people.

**Comment by rochford77** [comment]
Why Use Selenium when twitter has a wonderful api? the ability to monitor several users would be easier that way, yeah?

**Comment by NikhilDoWhile** [comment]
I am using twitter's API only.

**Comment by semaaJ** [comment]
I didn't use Selenium! I need to implement something to monitor several people at the one time, but it's really not too difficult to do.

["Twitter names go here"] should be a list on twitter handles ie: JohnSmith123 JohnSmith234 JohnJohn

Emails is the exact same, ie: JohnSmith@gmail.com Johnjohn@gmail.com test@gmail.com etc

**Comment by rochford77** [comment]
My mistake, looks like you are using it to scrape for company stock symbols.

**Comment by NikhilDoWhile** [comment]
**Is it our mail or the mail of people we want to monitor ?** 
**Is the twitter handle ==  email ?** ( is it in context of this app because it's not necessary that twitter handle would be email address )
And I think files section need not to be edited?
**Also if possible please add option to add multiple accounts.**

**Comment by semaaJ** [comment]
I really don't understand what you mean. The email file is a list of emails seperated by spaces that the script sends an email to when a company in mentioned, the twitter name file is a list of twitter handles which the script sends a dm to when a company in mentioned.

Files section doesn't need to be edited..

**Comment by NikhilDoWhile** [comment]
I wanted to know, can I monitor any other account else then of trump, and how to do so. Also could I add multiple accounts ?

**Comment by semaaJ** [comment]
Change the twitter name in the config file to the handle you want to monitor.

No idea what multiple accounts means?

**Comment by NikhilDoWhile** [comment]
This one ? 
![pr1](https://cloud.githubusercontent.com/assets/9911561/22531544/8e031bfc-e907-11e6-9b0b-f3f45c3a7b87.PNG)

**Comment by semaaJ** [comment]
No, " the twitter name file is a list of twitter handles which the script sends a dm to when a company in mentioned."

Within the CONFIG.JSON file, there is a TWITTER-AUTH section, replace REALDONALDTRUMP in that section with your preferred twitter handle.

**Comment by NikhilDoWhile** [comment]
This:
![pr2](https://cloud.githubusercontent.com/assets/9911561/22531809/66c9b8fa-e909-11e6-9974-23533a04bb91.PNG)

and could I add multiple accounts ?

**Comment by semaaJ** [comment]
Yes.

**Comment by NikhilDoWhile** [comment]
could I add multiple accounts ?

**Comment by semaaJ** [comment]
As said above no, the script doesn't allow it.

**Comment by NikhilDoWhile** [comment]
Thanx, for the feedback .Really helpful..
