### ISSUE TITLE
Error  repo: 2_2_17

### ISSUE THREAD

**Issue by NikhilDoWhile** [Mhyles/DonaldTrumpStockMonitor#11]
**Error Message on running Trump.py in Python-3**

![er3](https://cloud.githubusercontent.com/assets/9911561/22532993/41a5956e-e911-11e6-8b96-56a1507d4202.PNG)

![er5](https://cloud.githubusercontent.com/assets/9911561/22533013/652fed7c-e911-11e6-8804-a7376cd39bb6.PNG)

**Code (error):**
![er2](https://cloud.githubusercontent.com/assets/9911561/22533047/9b4a9f6a-e911-11e6-8181-9d04206d6055.PNG)

![er1](https://cloud.githubusercontent.com/assets/9911561/22533075/b8257e02-e911-11e6-8b42-f261fee7efed.PNG)

![er6](https://cloud.githubusercontent.com/assets/9911561/22533104/e76f4c10-e911-11e6-8ab8-54113171a017.PNG)

**Comment by semaaJ** [comment]
No idea why your getting that error, works perfectly for me.
