### ISSUE TITLE
monitor.json

### ISSUE THREAD

**Issue by NikhilDoWhile** [Mhyles/DonaldTrumpStockMonitor#12]
Is the format for monitor.json right: 

![e1](https://cloud.githubusercontent.com/assets/9911561/22533403/ff798422-e913-11e6-96ea-c12cbc6971d7.PNG)

**Comment by semaaJ** [comment]
Not at all, you don't put anything in there.

**Comment by NikhilDoWhile** [comment]
Fixed, tanks
