### ISSUE TITLE
doesnt work if @ before company name

### ISSUE THREAD

**Issue by Skeyelab** [Mhyles/DonaldTrumpStockMonitor#13]
Seems a recent tweet where DJT said "@intel" did not get picked up.  Maybe you should strip @ symbols from the tweet before checking it?

**Comment by semaaJ** [comment]
Yup, I'm going to add that now, thanks for that!

**Comment by Skeyelab** [comment]
that being said, I was thinking... maybe its better to maintain a list of known twitter handles, and explicitly check them against the @ symbol.

Thoughts?

**Comment by semaaJ** [comment]
I was thinking about doing this too. I'm going to heavily edit some of the code this week, and I think I'm going to add the twitter handles!
