### ISSUE TITLE
Create an application.

### ISSUE THREAD

**Issue by NikhilDoWhile** [Mhyles/DonaldTrumpStockMonitor#2]
**Can you please explain or post your configuration(blurring the private info), how to setup the Twitter OAuth and where to place the values in configuration inside the project ?** 

![t1](https://cloud.githubusercontent.com/assets/9911561/22103049/9d90eb42-de5f-11e6-945d-9182c6e52c5e.PNG)
![t2](https://cloud.githubusercontent.com/assets/9911561/22103050/9dd5c1f4-de5f-11e6-9e4f-82ca7dcbcde2.PNG)
![t3](https://cloud.githubusercontent.com/assets/9911561/22103051/9dd97c0e-de5f-11e6-8075-c4d1134652c2.PNG)

**Comment by semaaJ** [comment]
God I'm so new to this lol, I'm sorry. I put that info in the readme!

**Comment by DrewMcArthur** [comment]
Information on creating a Twitter app is already online, and can be easily found.  I'd suggest adding comments to the `config.json` file to make it clearer what info is needed from where.

Also, you could make the email part optional, just make sure the email signup list doesn't run if there's no email/password in config.json

**Comment by NikhilDoWhile** [comment]
Information is there but is not user friendly. What are we supposed to add for this project specifically, If there could be some documentation or screenshot of what has to be filled then it would be really easy to understand for any user,Even `config.json` file could be of help. It would save any one hours, which they will spend searching on internet.

**Comment by semaaJ** [comment]
I'll fix it all up now :)

**Comment by semaaJ** [comment]
Is it a little better now?

**Comment by NikhilDoWhile** [comment]
Yeah it's better now. Kudos for the work .

**Comment by semaaJ** [comment]
No problem, thank you for helping me improve this :)

**Comment by NikhilDoWhile** [comment]
Just one more thing. In twitter application, what has to be filled in **website** and can we write any name or it should be **DonaldTrumpStockMonitor** only ?


![t1](https://cloud.githubusercontent.com/assets/9911561/22119009/df95f24a-de9f-11e6-8a1d-a2a17ab09ae0.PNG)

**Comment by semaaJ** [comment]
Write anything, it doesnt matter :)
