### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by dgvisnadi** [Mhyles/DonaldTrumpStockMonitor#7]
Hi,

I am newbie. I followed your setup steps. 

Do I have to activate or call the python file or will I automatically get an email once Trump tweet mentions a company? 

Extra: I simply pip installed all three packages, cloned your repo and filled out the file with twitter tokens and email. 

Thanks for your help.

**Comment by semaaJ** [comment]
You need to leave it running all the time, but it will work. Otherwise you could sign up to my Twitter with your email/Twitter and you'll get updates!

**Comment by dgvisnadi** [comment]
But what you mean I have to leave it running? If I call the python file in the terminal I get an error message.

**Comment by semaaJ** [comment]
The script needs to be left running for it to work properly.

What is the error message?

**Comment by dgvisnadi** [comment]
Thanks for your help.

![screen shot 2017-01-21 at 17 27 20](https://cloud.githubusercontent.com/assets/10060398/22176300/02e673cc-dfff-11e6-9559-585c961d16ff.png)

**Comment by semaaJ** [comment]
Yeah, that's the error I thought it would be. I didn't put anything in there to encode the Twitter status to utf-8. I'll have to fix that, thanks for notifying me of this. May be tomorrow before I actually get to fixing that.

**Comment by semaaJ** [comment]
Give it a try with the updated files.

**Comment by dgvisnadi** [comment]
New error....
![screen shot 2017-01-22 at 19 11 47](https://cloud.githubusercontent.com/assets/10060398/22185084/d236be02-e0d6-11e6-93fe-04c3c62e2b9d.png)

**Comment by semaaJ** [comment]
Okay, that's a weird error. 

A google search brings back this: http://stackoverflow.com/questions/9156417/valid-json-giving-jsondecodeerror-expecting-delimiter

Try this: with open(r(config), "r") as f:
    config = json.load(f)

or: with open(r"./files/config.json", "r") as f:

**Comment by dgvisnadi** [comment]
It's working. The issue was when I pulled your changes I had some weird characters in the config.json file and that's why he couldnt read it.

**Comment by semaaJ** [comment]
Great, glad it's working. I'll be updating this daily until it's done, so keep an eye on it :)

**Comment by dgvisnadi** [comment]
Just to be clear, everytime Trump mentions a company I will receive an email as long as the Trump.py file is running, right? Thanks so much for your support!

**Comment by semaaJ** [comment]
And yes, you will. However, you can instead sign up to my script that I have running, and it will email you if you would prefer.
